### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by monicaSudarsanam** [cbg-ethz/BnpC#17]
Hello,

I tried to run the tool with python3.9 and my command was  ```python run_BnpC.py example_data/data.csv```
and this had returned me the following error. I would appreciate any help with running this tool. Thank you very much and look forward to your reply.

```Run MCMC with (1 chains for 5000 steps):
Traceback (most recent call last):
  File "/Volumes/Monica_data_folder/bnpc_software/BnpC/run_BnpC.py", line 295, in <module>
    main(args)
  File "/Volumes/Monica_data_folder/bnpc_software/BnpC/run_BnpC.py", line 287, in main
    results = mcmc.get_results()
  File "/Volumes/Monica_data_folder/bnpc_software/BnpC/libs/MCMC.py", line 65, in get_results
    if not 'burn_in' in results[0]:
IndexError: list index out of range```

**Comment by NBMueller** [comment]
Dear Monica,
Somewhere in the scipy history, some things were changed that resulted in an underflow error in our implementation.
I fixed it and updated the requirements, please have another try and let me know if it still fails.
Best,
Nico

**Comment by monicaSudarsanam** [comment]
Thanks Nico, It works perfectly now :) :100: :1st_place_medal:
