### ISSUE TITLE
genoCluster_posterior_mean.png doesnot display the correct row ids

### ISSUE THREAD

**Issue by monicaSudarsanam** [cbg-ethz/BnpC#25]
Hi Bnpc support,

I have used row ids and cell IDs in the input and then the resulting heatmap "genoCluster_posterior_mean.png" from it contains the row ids in the exactly same order as the input. But from the image, we could easily say that the rows were sorted and the order of rows had been changed. The order of the row ids is not in the same way as the input but the row ids display the same order as the input. Is there something that I am doing wrong? Do you happen to have a solution for this?

Thanks a lot in advance.

Best,
Monica.

**Comment by NBMueller** [comment]
Dear Monica,

A little late but it was a little buggy and should be fixed now. Additionally, I changed the output format to pdf; full row and column names should be readable now.

Cheers
